# Generated by Django 4.2.11 on 2024-06-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img2pdf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
