# Generated by Django 4.2.11 on 2024-06-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img2pdf', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
